# Generated by Django 6.0.3 on 2026-03-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='published_at',
            field=models.DateTimeField(verbose_name='Дата выхода'),
        ),
    ]
