# Generated by Django 6.0.5 on 2026-05-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_generator', '0002_alter_actor_options_alter_actor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='movie_generator.tag'),
        ),
    ]
