# Generated by Django 6.0.5 on 2026-06-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_generator', '0003_add_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на трейлер'),
        ),
    ]
