# Generated by Django 6.0.5 on 2026-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_generator', '0005_remove_movie_trailer_url_movie_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на трейлер'),
        ),
    ]
